# GenerateJSConstants.ps1
#
# Reads the JS source files in Source/InoWebUI/JS/ and emits all three:
#   - Source/InoWebUI/Private/Generated/InoWebUIScripts.generated.h        (C++ — Win64 + Android)
#   - Source/InoWebUI/Private/Generated/InoWebUIScripts_iOS.generated.h    (Obj-C++ NSString — iOS)
#   - Source/InoWebUI/Java/src/net/inoland/webui/InoWebUIScripts.java      (Java — Android)
#
# Re-run any time you edit one of the .js files. The output files are
# committed to source control so a fresh checkout builds without the script.

$ErrorActionPreference = 'Stop'

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$PluginRoot = (Resolve-Path (Join-Path $ScriptDir '..')).Path
$JsDir      = Join-Path $PluginRoot 'Source/InoWebUI/JS'
$CppOut     = Join-Path $PluginRoot 'Source/InoWebUI/Private/Generated/InoWebUIScripts.generated.h'
$IOSOut     = Join-Path $PluginRoot 'Source/InoWebUI/Private/Generated/InoWebUIScripts_iOS.generated.h'
$JavaOut    = Join-Path $PluginRoot 'Source/InoWebUI/Java/src/net/inoland/webui/InoWebUIScripts.java'

$Bundles = @(
    @{ File = 'bridge.js';      CppName = 'GInoWebUIBridgeScript';          JavaName = 'BRIDGE_JS';            ObjCName = 'GInoWebUIBridgeScript' },
    @{ File = 'dev_overlay.js'; CppName = 'GInoWebUIDevToolsOverlayScript'; JavaName = 'DEVTOOLS_OVERLAY_JS';  ObjCName = 'GInoWebUIDevToolsOverlayScript' },
    @{ File = 'notify_overlay.js'; CppName = 'GInoWebUINotifyOverlayScript'; JavaName = 'NOTIFY_OVERLAY_JS'; ObjCName = 'GInoWebUINotifyOverlayScript' },
    # iOS-only: the pageWorld ↔ defaultClientWorld relay/shim. Not emitted
    # into the C++/Java constant files (Win64 and Android don't need it —
    # they use bridge.js directly in their single-world model).
    @{ File = 'bridge_ios.js';  ObjCName = 'GInoWebUIIOSWorldBridgeScript'; IOSOnly = $true }
)

# MSVC's hard limit on a single string-literal token is 16380 chars. We chunk
# at ~8000 so we stay well under that and keep diffs readable. The C
# preprocessor concatenates adjacent string literals at compile time, so
# splitting is free at runtime.
$CppChunkBytes = 8000

function Read-JsFile([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path)) { throw "Missing source: $Path" }
    $text = [System.IO.File]::ReadAllText($Path, [System.Text.Encoding]::UTF8)
    return ($text -replace "`r`n", "`n")
}

function Get-Chunks([string]$Text, [int]$MaxBytes) {
    $lines = $Text -split "`n"
    $chunks = New-Object 'System.Collections.Generic.List[string]'
    $current = New-Object System.Text.StringBuilder
    foreach ($line in $lines) {
        $needed = $current.Length + $line.Length + 1
        if ($current.Length -gt 0 -and $needed -gt $MaxBytes) {
            [void]$chunks.Add($current.ToString())
            $current = New-Object System.Text.StringBuilder
        }
        if ($current.Length -gt 0) { [void]$current.Append("`n") }
        [void]$current.Append($line)
    }
    if ($current.Length -gt 0) { [void]$chunks.Add($current.ToString()) }
    return ,$chunks
}

function ConvertTo-JavaString([string]$Text) {
    $sb = New-Object System.Text.StringBuilder
    foreach ($ch in $Text.ToCharArray()) {
        switch ($ch) {
            '\'  { [void]$sb.Append('\\') }
            '"'  { [void]$sb.Append('\"') }
            "`n" { [void]$sb.Append('\n') }
            "`t" { [void]$sb.Append('\t') }
            default { [void]$sb.Append($ch) }
        }
    }
    return $sb.ToString()
}

# Apple's clang accepts arbitrarily long NSString literals (no MSVC-style 16380
# limit), so we don't have to chunk. Same character escapes as Java/C — the
# subset we use stays identical: backslash, quote, \n, \r, \t, \b, \f, \?
# (\? avoids C trigraph interpretation in case the JS contains "??=" etc.).
function ConvertTo-ObjCString([string]$Text) {
    $sb = New-Object System.Text.StringBuilder
    foreach ($ch in $Text.ToCharArray()) {
        switch ($ch) {
            '\'  { [void]$sb.Append('\\') }
            '"'  { [void]$sb.Append('\"') }
            "?"  { [void]$sb.Append('\?') }
            "`n" { [void]$sb.Append('\n') }
            "`r" { [void]$sb.Append('\r') }
            "`t" { [void]$sb.Append('\t') }
            default {
                $code = [int][char]$ch
                if ($code -lt 0x20) {
                    # Control char — hex escape so it survives compilation.
                    [void]$sb.AppendFormat('\x{0:x2}', $code)
                } else {
                    [void]$sb.Append($ch)
                }
            }
        }
    }
    return $sb.ToString()
}

$nl = "`r`n"
$utf8NoBOM = New-Object System.Text.UTF8Encoding $false

# ── C++ header ────────────────────────────────────────────────────────────
$cpp = ''
$cpp += '// Copyright 2026 Inoland. Licensed under the Apache License, Version 2.0.' + $nl
$cpp += '// AUTO-GENERATED by Plugins/InoWebUI/Scripts/GenerateJSConstants.ps1' + $nl
$cpp += '// Source: Plugins/InoWebUI/Source/InoWebUI/JS/*.js' + $nl
$cpp += '// Edit the .js files and re-run the script to regenerate.' + $nl + $nl
$cpp += '#pragma once' + $nl + $nl

foreach ($b in $Bundles) {
    if ($b.IOSOnly) { continue }
    $jsPath = Join-Path $JsDir $b.File
    $content = Read-JsFile $jsPath

    # Defensive: the C++ raw-literal terminator is `)JS"`. If the JS source
    # ever contains that exact substring (it shouldn't — JS doesn't use it),
    # the literal would terminate early and produce garbage.
    if ($content.Contains(')JS"')) {
        throw ('Source {0} contains the substring ")JS""" which would terminate the C++ raw string early. Pick a different terminator and update both files.' -f $jsPath)
    }

    $chunks = Get-Chunks $content $CppChunkBytes
    $cpp += ('// Generated from {0}' -f $b.File) + $nl
    $cpp += ('static const TCHAR* {0} =' -f $b.CppName) + $nl
    for ($i = 0; $i -lt $chunks.Count; $i++) {
        $tail = if ($i -eq $chunks.Count - 1) { ';' } else { '' }
        $cpp += ('    TEXT(R"JS({0})JS"){1}' -f $chunks[$i], $tail) + $nl
    }
    $cpp += $nl
}

$null = New-Item -ItemType Directory -Force -Path (Split-Path $CppOut) | Out-Null
[System.IO.File]::WriteAllText($CppOut, $cpp, $utf8NoBOM)
Write-Host ('Wrote ' + $CppOut)

# ── Java class ────────────────────────────────────────────────────────────
$java = ''
$java += '// Copyright 2026 Inoland. Licensed under the Apache License, Version 2.0.' + $nl
$java += '// AUTO-GENERATED by Plugins/InoWebUI/Scripts/GenerateJSConstants.ps1' + $nl
$java += '// Source: Plugins/InoWebUI/Source/InoWebUI/JS/*.js' + $nl
$java += '// Edit the .js files and re-run the script to regenerate.' + $nl + $nl
$java += 'package net.inoland.webui;' + $nl + $nl
$java += 'public final class InoWebUIScripts' + $nl + '{' + $nl
$java += '    private InoWebUIScripts() {}' + $nl + $nl

foreach ($b in $Bundles) {
    if ($b.IOSOnly) { continue }
    $jsPath = Join-Path $JsDir $b.File
    $content = Read-JsFile $jsPath
    $escaped = ConvertTo-JavaString $content
    $java += ('    /** Generated from {0} */' -f $b.File) + $nl
    $java += ('    public static final String {0} = "{1}";' -f $b.JavaName, $escaped) + $nl + $nl
}
$java += '}' + $nl

$null = New-Item -ItemType Directory -Force -Path (Split-Path $JavaOut) | Out-Null
[System.IO.File]::WriteAllText($JavaOut, $java, $utf8NoBOM)
Write-Host ('Wrote ' + $JavaOut)

# ── Objective-C++ header (iOS) ────────────────────────────────────────────
# Emits NSString literal constants for the iOS impl to feed to
# WKUserScript / evaluateJavaScript. Apple's clang has no MSVC-style
# string-literal length limit, so a single long literal is fine.
$objc = ''
$objc += '// Copyright 2026 Inoland. Licensed under the Apache License, Version 2.0.' + $nl
$objc += '// AUTO-GENERATED by Plugins/InoWebUI/Scripts/GenerateJSConstants.ps1' + $nl
$objc += '// Source: Plugins/InoWebUI/Source/InoWebUI/JS/*.js' + $nl
$objc += '// Edit the .js files and re-run the script to regenerate.' + $nl + $nl
$objc += '#pragma once' + $nl + $nl
$objc += '#import <Foundation/Foundation.h>' + $nl + $nl

foreach ($b in $Bundles) {
    $jsPath  = Join-Path $JsDir $b.File
    $content = Read-JsFile $jsPath
    $escaped = ConvertTo-ObjCString $content
    $objc += ('// Generated from {0}' -f $b.File) + $nl
    $objc += ('static NSString* const {0} = @"{1}";' -f $b.ObjCName, $escaped) + $nl + $nl
}

$null = New-Item -ItemType Directory -Force -Path (Split-Path $IOSOut) | Out-Null
[System.IO.File]::WriteAllText($IOSOut, $objc, $utf8NoBOM)
Write-Host ('Wrote ' + $IOSOut)
